### ISSUE TITLE
Unable to exclude from coverage

### ISSUE THREAD

**Issue by wdm954** [cypress-io/instrument-cra#123]
I cloned the example from here: https://github.com/bahmutov/testing-react

I added `nyc` to the `package.json`:

    {
        ...
        "scripts": {
            ...
            "start-dev": "react-scripts -r @cypress/instrument-cra start"
            ...
        },
        ...
        "nyc": {
            "exclude": "src/constants/actionTypes.js"
        }
    }

However I'm still seeing this file in `window.__coverage__`:

    /.../testing-react/src/constants/actionTypes.js: {path: "/.../testing-react/src/constants/actionTypes.js", statementMap: {…}, fnMap: {…}, branchMap: {…}, s: {…}, …}

Am I missing something?

**Comment by bahmutov** [comment]
Hi @wdm954 

You can still have extra covered files in the `window.__coverage__` file, but they will be filtered when the report is generated
