### ISSUE TITLE
Particular React code not being counted

### ISSUE THREAD

**Issue by coobr01** [cypress-io/instrument-cra#148]
Great library! Our team is wondering if there would be a reason this type of code is not getting counted when we have tests that run it? Something to do with the single line return statement? 

Thanks!

![image](https://user-images.githubusercontent.com/1842830/82440729-d3de6600-9a6a-11ea-9d91-d8e8d87c86ce.png)

**Comment by bahmutov** [comment]
good question, while I don't have time to investigate, it is probably something nyc does where it does not consider those statements as "executable" and only as definitions
