### ISSUE TITLE
How to execute without using "-r @cypress/instrument-cra start" ?

### ISSUE THREAD

**Issue by lucas-v-s** [cypress-io/instrument-cra#170]
Our devops is implementing it inside a docker container and we had to start the application directly from react scripts using forever, like:

```forever start node_modules\react-scripts\scripts\start.js```

and then run cypress tests, but we couldn't instrument using like if we were using yarn start (react-scripts -r @cypress/instrument-cra start)

so, by the way we are running our tests, is it possible to instrumento using another approach? If we run locally with react-scripts -r @cypress/instrument-cra start it works perfectly.

**Comment by bahmutov** [comment]
Same way: you use `node` and the start script and insert this module in between them

```
forever start node -r @cypress/instrument-cra node_modules\react-scripts\scripts\start.js
```

**Comment by lucas-v-s** [comment]
> Same way: you use `node` and the start script and insert this module in between them
> 
> ```
> forever start node -r @cypress/instrument-cra node_modules\react-scripts\scripts\start.js
> ```

Thanks a lot for the answer, i didn't even think about calling node here. 
Worked fine.

---
In case someone runs into this:
forever -c "node -r @cypress/instrument-cra" start node_modules/react-scripts/scripts/start.js
