### ISSUE TITLE
Usage with monorepo 

### ISSUE THREAD

**Issue by jalal246** [cypress-io/instrument-cra#172]
I am using `@cypress/instrument-cra` in monorepo, with `yarn workspace` to symlink packages. 

```
/pkg1
/pkg2
/pkg3
     - react-app
     - cypress
     - src
     - package.json
```

code coverage works fine, but i need to collect coverage for packages used in `react-app`. Inside react components i am importing src packages as following:

```js
import pkg1 from @myProject/pkg1
```

The problem is `pkg1` is not included in the coverage report. I tried to include `node_modules` in `nyc` but it didn't work.

```json
"nyc": {
  "all": true,
  "include": [
    "node_modules"
  ],
  "excludeNodeModules": false
} 
```

Is there an example to work with monorepo?  In `Jest` i can use `collectCoverageFrom` but how i can do it here.

**Comment by kkgowtamasa** [comment]
Is there a solution to this problem? @bahmutov this is what even I'm looking for.
