### ISSUE TITLE
JS files that aren't loaded by webpack are not included in the coverage report

### ISSUE THREAD

**Issue by brightpixels** [cypress-io/instrument-cra#209]
Hello,
I have a fresh React app scaffolded using `create-react-app` (CRA) for the purposes of testing how to generate coverage reports using cypress.

I created a new first component called `List.js` in `src` folder and I generated a coverage report, however I don't see it this component listed in the report (see attached images). The only time it is included in the coverage report is when I imported `'List.js` component into `index.js` or `App.js`, otherwise it's not in the report (See images).

In one of Gleb's videos, you can see for example `serviceWorker.js` file showing in the report https://youtu.be/y8StkffYra0?t=154. So in a similar way, I am expecting all JS files in `src` folder to be part of the report by default unless I somehow exclude them.

This is how my package.json looks like:

````
....

"scripts": {
    "start": "react-scripts -r @cypress/instrument-cra start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "cypress:wait": "start-server-and-test start http://localhost:3000",
    "cypress:open": "npm run cypress:wait -- \"cypress open\" ",
    "cypress:run": "npm run cypress:wait -- \"cypress run\" "
  }

....
````

Report following creationg of `src/List.js` (without importing it anywhere)
![PixelSnap 2021-01-07 at 02 14 47@2x](https://user-images.githubusercontent.com/5403134/103842643-52395800-508e-11eb-9445-f83a2c7b6989.png)

![PixelSnap 2021-01-07 at 02 15 15@2x](https://user-images.githubusercontent.com/5403134/103842648-55ccdf00-508e-11eb-816e-519424dfaa41.png)

After importing `src/List.js` into App.js
![PixelSnap 2021-01-07 at 02 20 14@2x](https://user-images.githubusercontent.com/5403134/103843008-eacfd800-508e-11eb-8eb7-d149c6a9b541.png)

**Comment by bahmutov** [comment]
You would need to include all expected files in the report by setting `nyc` object, see https://github.com/cypress-io/code-coverage#include-code

**Comment by brightpixels** [comment]
That works. Thanks. Is it possible that the coverage percentage also accounts for untested lines of code in files that aren't used/imported anywhere like List.js in image below? This would prompt devs to either test the file or remove it as it's no longer needed.

![PixelSnap 2021-01-08 at 19 05 20@2x](https://user-images.githubusercontent.com/5403134/104054153-7b6bfc80-51e4-11eb-97d3-b12d9c82e315.png)


![PixelSnap 2021-01-08 at 18 50 28@2x](https://user-images.githubusercontent.com/5403134/104053348-f7654500-51e2-11eb-8291-ccacd8a4ee1a.png)

**Comment by bahmutov** [comment]
@brightpixels see https://github.com/cypress-io/code-coverage#contributing - `nyc report` is very forgiving and ignores empty files, but you can use https://github.com/bahmutov/check-code-coverage to check it and fail the test if any files are not covered
