### ISSUE TITLE
nyc paths in out.json

### ISSUE THREAD

**Issue by ShamansCoding** [cypress-io/instrument-cra#22]
Greetings! 

I've encountered a problem with collected coverage with paths in .out.json

All of them starts with /app/src/...

And coverage could not be collected properly as nyc produces an error:

Unable to lookup source: /app/src/Components/App/index.jsx(ENOENT: no such file or directory, open '/app/src/Components/App/index.jsx')

If I change the paths to ./src and create the report manually with nyc v13
everything seems to be working properly.

My app has a standard layout, created by RCA and all my source code is located in the src directory.

Might it be related to issue with nyc 14.1.1 bug?
https://github.com/cypress-io/code-coverage/issues/65

**Comment by bahmutov** [comment]
Try upgrading to latest dependencies and see if this solves the issue.

**Comment by bahmutov** [comment]
assuming resolved
