### ISSUE TITLE
React-scripts flag vs customize-cra

### ISSUE THREAD

**Issue by zorgick** [cypress-io/instrument-cra#220]
Hi, my question is about integrating your package into react-scripts process. 

I've looked through the [react-scripts code](https://github.com/facebook/create-react-app/tree/master/packages/react-scripts), but I didn't find any notice about the `-r` argument, that your package relies on.

So, I have some considerations, whether your decision to use that flag is more reliable, than to use [react-app-rewired](https://github.com/timarney/react-app-rewired/) with [customize-cra](https://github.com/arackaf/customize-cra) and separate babelrc config.

Also, could you, please, tell me, where exactly did you find that flag?

**Comment by bahmutov** [comment]
Look at the code in https://github.com/facebook/create-react-app/blob/0ee4765c39f820e5f4820abf4bf2e47b3324da7f/packages/react-scripts/bin/react-scripts.js#L21-L33 and trace what happens when you call `react-scripts -r moduleName start` for example - it runs Node with `-r moduleName` then the react scripts JS file

**Comment by zorgick** [comment]
Yes, I see now. I lack knowledge in node arguments. Apparently, I thought that the flag belongs to react-scripts, not directly to node. Thanks for the help!

**Comment by zorgick** [comment]
@bahmutov Although, I have a problem that have already been mentioned in [issues](https://github.com/cypress-io/instrument-cra/issues/188). Here, [nyc.exclude rule](https://github.com/zorgick/lerna-bootstrap/blob/3afabecb2ddffea92ba31b44e7a0b0cebe610006/packages/web/package.json#L58) in package.json is ignored, when this package is used with react-scripts. 

However, if I use react-app-wired with customize-cra and babel-plugin-istanbul in a separate  [.babelrc file](https://github.com/zorgick/lerna-bootstrap/blob/ff942043ebfeaef442691108804379c6bc9c992b/packages/web/.babelrc#L1-L9), everything works as expected, and the coverage is not collected for excluded files.
